import sys
import os
from typing import Optional, Tuple, Dict, Any
# Add the parent directory to the sys.path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from common_utils.sequence import *
import json
from langchain.tools import tool

@tool()
def get_sequence_info(path: str) -> Dict[str, Any]:
    """
    读取文件并返回其中除了sequence之外的SequenceRecord信息。
    
    Args:
        path (str): 文件路径，应该是一个 JSON 文件，包含 SequenceRecord 数据。

    Returns:
        Dict[str, Any]: 包含 SequenceRecord 的信息，但不包括 'sequence' 字段。
    """
    # we need to read that JSON file.
    json_path = path
    with open(json_path, "r", encoding="utf-8") as f:
        record = json.load(f)
    
    # Create a copy and remove the 'sequence' field
    if "sequence" in record:
        del record["sequence"]
    
    return record

if __name__ == "__main__":
    # The load_sequence function expects a .dna file and returns the path to the generated JSON.
    # We need to pass the original .dna file path here.
    dna_file_path = "D:/github_repo/PPversion2/data/temp/pcDNA3.1(-).json"
    # First, ensure the JSON is generated by calling load_sequence
    # The get_sequence_info function will then read this generated JSON.
    res = get_sequence_info(dna_file_path)
    print(res)
